import Stripe from 'stripe';
import { STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET } from '$env/static/private';
import { sendReceiptEmail } from '$lib/server/email';
import { supabase } from '$lib/server/supabaseServiceClient';
import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

const stripe = new Stripe(STRIPE_SECRET_KEY, { apiVersion: '2026-01-28.clover' });

export const POST: RequestHandler = async ({ request }) => {
  const body = await request.text();
  const signature = request.headers.get('stripe-signature') ?? '';

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(body, signature, STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    console.error('Webhook signature verification failed:', err);
    return json({ error: 'Invalid signature' }, { status: 400 });
  }

  if (event.type === 'checkout.session.completed' ||
    event.type === 'checkout.session.async_payment_succeeded') {
  const session = event.data.object as Stripe.Checkout.Session;
  const { participant_id, type } = session.metadata ?? {};

  if (!participant_id) {
    console.error('Webhook missing participant_id in metadata');
    return json({ error: 'Missing metadata' }, { status: 400 });
  }

  // Resolve the py_ charge ID (what Stripe dashboard shows) from the pi_ payment intent
  const paymentIntentId = session.payment_intent as string;
  let chargeId: string | null = null;
  if (paymentIntentId) {
    const pi = await stripe.paymentIntents.retrieve(paymentIntentId);
    chargeId = typeof pi.latest_charge === 'string' ? pi.latest_charge : (pi.latest_charge as any)?.id ?? null;
  }

  const isAccommodationPayment = type?.startsWith('accommodation_');

  // Only mark participant_products as paid for ticket/product payments
  // Accommodation payments are tracked separately in hotel_bookings
  if (!isAccommodationPayment) {
    // Mark pending products as paid and capture which rows were affected
    const { data: justPaidProducts, error } = await supabase
      .from('participant_products')
      .update({
        payment_status: 'paid',
        updated_at: new Date().toISOString()
      })
      .eq('participant_id', participant_id)
      .eq('payment_status', 'pending')
      .select('id, product_name, unit_price, quantity_ordered, subtotal, mva_rate, mva_amount, currency_type');

    if (error) {
      console.error('Failed to update payment_status:', error);
      return json({ error: 'DB update failed' }, { status: 500 });
    }

    await supabase
      .from('event_participants')
      .update({ stripe_payment_intent_id: paymentIntentId })
      .eq('id', participant_id);

    // Build totals for the invoice
    const products = justPaidProducts ?? [];
    const totalInclMva = products.reduce((sum, p) => sum + Number(p.subtotal), 0);
    const totalMva     = products.reduce((sum, p) => sum + Number(p.mva_amount ?? 0), 0);
    const totalExclMva = totalInclMva - totalMva;
    const currency     = products[0]?.currency_type ?? 'NOK';

    // Create the invoice record (invoice_number auto-generated by DB function)
    const { data: invoice, error: invoiceErr } = await supabase
      .from('invoices')
      .insert({
        participant_id,
        stripe_payment_intent_id: paymentIntentId,
        stripe_charge_id: chargeId,
        stripe_session_id: session.id,
        buyer_name: session.metadata?.buyer_name ?? null,
        buyer_email: session.customer_details?.email ?? null,
        total_excl_mva: Math.round(totalExclMva * 100) / 100,
        total_mva:      Math.round(totalMva * 100) / 100,
        total_incl_mva: Math.round(totalInclMva * 100) / 100,
        currency
      })
      .select('id, invoice_number')
      .single();

    if (invoiceErr) {
      console.error('Failed to create invoice record:', invoiceErr);
    } else if (invoice && products.length > 0) {
      // Link each paid product row to this invoice
      const productIds = products.map(p => p.id);
      await supabase
        .from('participant_products')
        .update({ invoice_id: invoice.id })
        .in('id', productIds);
    }

    // Send Norwegian-compliant receipt email
    try {
      const { data: participant } = await supabase
        .from('event_participants')
        .select('user_id, event_id, profiles ( username ), events ( title, start_date )')
        .eq('id', participant_id)
        .single();

      const { data: authUser } = await supabase.auth.admin.getUserById(
        participant?.user_id ?? ''
      );

      const email = authUser?.user?.email ?? session.customer_details?.email;

      // Fetch the Stripe-connected event director's organizer info for the seller block
      let seller = { name: 'Event Organizer' as string, orgNumber: null as string | null, address: null as string | null, email: null as string | null };
      if (participant?.event_id) {
        // Step 1: Get all Event Directors for this event
        const { data: edRows } = await supabase
          .from('event_participants')
          .select('user_id')
          .eq('event_id', participant.event_id)
          .eq('event_role', 'Event Director');

        const edUserIds = (edRows ?? []).map(r => r.user_id);

        if (edUserIds.length > 0) {
          // Step 2: Find the one who has Stripe connected (same logic as checkout server)
          const { data: stripeProfiles } = await supabase
            .from('profiles')
            .select('id, username, organizer_name, organizer_org_number, organizer_address, organizer_email')
            .in('id', edUserIds)
            .eq('stripe_onboarding_complete', true)
            .not('stripe_account_id', 'is', null)
            .limit(1);

          const edProfile = stripeProfiles?.[0];
          if (edProfile) {
            seller = {
              name:      edProfile.organizer_name || edProfile.username || 'Event Organizer',
              orgNumber: edProfile.organizer_org_number ?? null,
              address:   edProfile.organizer_address ?? null,
              email:     edProfile.organizer_email ?? null
            };
          }
        }
      }

      if (email && participant && invoice) {
        await sendReceiptEmail({
          to: email,
          invoiceNumber: invoice.invoice_number,
          buyerName: (participant.profiles as any)?.username ?? session.metadata?.buyer_name ?? 'Deltaker',
          eventTitle: (participant.events as any)?.title ?? 'Arrangement',
          seller,
          products: products.map(p => ({
            name:       p.product_name,
            quantity:   p.quantity_ordered,
            unitPrice:  Number(p.unit_price),
            subtotal:   Number(p.subtotal),
            mvaRate:    Number(p.mva_rate ?? 0),
            mvaAmount:  Number(p.mva_amount ?? 0)
          })),
          totalExclMva: Math.round(totalExclMva * 100) / 100,
          totalMva:     Math.round(totalMva * 100) / 100,
          totalInclMva: Math.round(totalInclMva * 100) / 100,
          currency,
          stripeRef: session.payment_intent as string,
          participantId: participant_id
        });
      }
    } catch (emailErr) {
      console.error('Failed to send receipt email:', emailErr);
    }
  }

  // Accommodation payment handling
  if (isAccommodationPayment) {
    const hotelBookingId = session.metadata?.hotel_booking_id;

    if (!hotelBookingId) {
      console.error('Webhook missing hotel_booking_id in metadata');
      return json({ error: 'Missing hotel_booking_id' }, { status: 400 });
    }

    // Update booking status
    let bookingUpdateError: any = null;
    if (type === 'accommodation_full') {
      const { error } = await supabase.from('hotel_bookings').update({
        deposit_paid: true, remaining_paid: true, remaining_amount: 0,
        updated_at: new Date().toISOString()
      }).eq('id', hotelBookingId);
      bookingUpdateError = error;
    } else if (type === 'accommodation_deposit') {
      const { error } = await supabase.from('hotel_bookings').update({
        deposit_paid: true, updated_at: new Date().toISOString()
      }).eq('id', hotelBookingId);
      bookingUpdateError = error;
    } else if (type === 'accommodation_remaining') {
      const { error } = await supabase.from('hotel_bookings').update({
        remaining_paid: true, updated_at: new Date().toISOString()
      }).eq('id', hotelBookingId);
      bookingUpdateError = error;
    }

    if (bookingUpdateError) {
      console.error('Failed to update hotel_bookings status:', bookingUpdateError);
    }

    // Create invoice + send receipt for accommodation payments
    if (hotelBookingId && participant_id) {
      try {
        // Fetch booking with product MVA rate
        const { data: hotelBooking } = await supabase
          .from('hotel_bookings')
          .select('*, products ( mva_rate )')
          .eq('id', hotelBookingId)
          .single();

        if (hotelBooking) {
          // Determine what was charged in this transaction
          let chargedAmount: number;
          let lineItemName: string;

          if (type === 'accommodation_full') {
            chargedAmount = parseFloat(hotelBooking.total_amount);
            lineItemName = `${hotelBooking.room_name} — Full Payment`;
          } else if (type === 'accommodation_deposit') {
            chargedAmount = parseFloat(hotelBooking.deposit_amount);
            lineItemName = `${hotelBooking.room_name} — Deposit`;
          } else {
            chargedAmount = parseFloat(hotelBooking.remaining_amount);
            lineItemName = `${hotelBooking.room_name} — Remaining Balance`;
          }
          if (hotelBooking.nights) {
            lineItemName += ` (${hotelBooking.nights} night${hotelBooking.nights === 1 ? '' : 's'})`;
          }

          const mvaRate       = Number((hotelBooking.products as any)?.mva_rate ?? 0);
          const mvaAmount     = Math.round(chargedAmount * mvaRate / (100 + mvaRate) * 100) / 100;
          const amountExclMva = Math.round((chargedAmount - mvaAmount) * 100) / 100;
          const currency      = hotelBooking.currency ?? 'NOK';

          // Create invoice record
          const { data: hotelInvoice } = await supabase
            .from('invoices')
            .insert({
              participant_id,
              hotel_booking_id: hotelBookingId,
              stripe_payment_intent_id: paymentIntentId,
              stripe_charge_id: chargeId,
              stripe_session_id: session.id,
              buyer_name:  session.metadata?.buyer_name ?? null,
              buyer_email: session.customer_details?.email ?? null,
              total_excl_mva: amountExclMva,
              total_mva:      mvaAmount,
              total_incl_mva: chargedAmount,
              currency
            })
            .select('id, invoice_number')
            .single();

          // Fetch participant for email + seller lookup
          const { data: hotelParticipant } = await supabase
            .from('event_participants')
            .select('user_id, event_id, profiles ( username ), events ( title )')
            .eq('id', participant_id)
            .single();

          const { data: hotelAuthUser } = await supabase.auth.admin.getUserById(
            hotelParticipant?.user_id ?? ''
          );
          const hotelEmail = hotelAuthUser?.user?.email ?? session.customer_details?.email;

          // Fetch Stripe-connected ED for seller block
          let hotelSeller = { name: 'Event Organizer' as string, orgNumber: null as string | null, address: null as string | null, email: null as string | null };
          if (hotelParticipant?.event_id) {
            const { data: edRows } = await supabase
              .from('event_participants')
              .select('user_id')
              .eq('event_id', hotelParticipant.event_id)
              .eq('event_role', 'Event Director');

            const edUserIds = (edRows ?? []).map(r => r.user_id);
            if (edUserIds.length > 0) {
              const { data: stripeProfiles } = await supabase
                .from('profiles')
                .select('id, username, organizer_name, organizer_org_number, organizer_address, organizer_email')
                .in('id', edUserIds)
                .eq('stripe_onboarding_complete', true)
                .not('stripe_account_id', 'is', null)
                .limit(1);

              const edProfile = stripeProfiles?.[0];
              if (edProfile) {
                hotelSeller = {
                  name:      edProfile.organizer_name || edProfile.username || 'Event Organizer',
                  orgNumber: edProfile.organizer_org_number ?? null,
                  address:   edProfile.organizer_address ?? null,
                  email:     edProfile.organizer_email ?? null
                };
              }
            }
          }

          if (hotelEmail && hotelInvoice) {
            await sendReceiptEmail({
              to:            hotelEmail,
              invoiceNumber: hotelInvoice.invoice_number,
              buyerName:     (hotelParticipant?.profiles as any)?.username ?? session.metadata?.buyer_name ?? 'Guest',
              eventTitle:    (hotelParticipant?.events as any)?.title ?? 'Accommodation',
              seller:        hotelSeller,
              products: [{
                name:      lineItemName,
                quantity:  1,
                unitPrice: chargedAmount,
                subtotal:  chargedAmount,
                mvaRate,
                mvaAmount
              }],
              totalExclMva:  amountExclMva,
              totalMva:      mvaAmount,
              totalInclMva:  chargedAmount,
              currency,
              stripeRef:     session.payment_intent as string,
              participantId: participant_id
            });
          }
        }
      } catch (hotelReceiptErr) {
        console.error('Failed to create hotel invoice/receipt:', hotelReceiptErr);
      }
    }
  }
}

if (event.type === 'checkout.session.async_payment_failed') {
  const session = event.data.object as Stripe.Checkout.Session;
  const { participant_id, type } = session.metadata ?? {};

  // Only cancel participant_products for non-accommodation failures
  if (participant_id && !type?.startsWith('accommodation_')) {
    await supabase
      .from('participant_products')
      .update({
        payment_status: 'cancelled',
        updated_at: new Date().toISOString()
      })
      .eq('participant_id', participant_id)
      .eq('payment_status', 'pending');
  }
}

  return json({ received: true });
};